### ISSUE TITLE
newbie question: connecting to existing sqlite database

### ISSUE THREAD

**Issue by mwiacko** [andyhu/waterline-nedb#1]
I'm trying to connect to existing sqlite database and in dbpath I setting path to this database. Sails keep saying that I should give a empty directory, which I assumed should do only for new db

**Comment by andyhu** [comment]
Hi, thanks for using this plugin. However it is an adapter of Nedb (https://github.com/louischatriot/nedb), not sqlite. If you need to use sqlite please try https://github.com/AndrewJo/sails-sqlite3/tree/0.10

**Comment by mwiacko** [comment]
Thank you very much
