### ISSUE TITLE
Tests work well?

### ISSUE THREAD

**Issue by monaka** [andyhu/waterline-nedb#6]
Please let me make sure.
I looks all tests are not for NeDB but for MongoDB. Test supports are WIP?

**Comment by andyhu** [comment]
Hi, I'm not quite sure, This project was created many years ago and no I'm not using sails.js any more.

**Comment by monaka** [comment]
I see.
In my usage, tests don't pass but works well on the latest Sails.
Thanks for your reply and your nice product.
